name: workflow Evento
on: 
  workflow_dispatch: 
    inputs:
      exemplo-inputs:
        type: string
        description: "Teste de input"
        requered: true
jobs:
  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Action de teste 
        run: echo "${{ inputs.exemplo-inputs }}"
      
